### ISSUE TITLE
ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by brajt** [stubailo/meteor-dev-error-overlay#1]
I love the idea of this package, but I have a slight problem to make it work.

I get the `ReferenceError: localStorage is not defined` message in the server console. I see that localStorage is not defined in the source code, so I guess it has to be provided from outside. What can I be missing? Some package which is not included in the dependencies?

```
ReferenceError: localStorage is not defined
     at loadConfig (dev-error-overlay.js:159:16)
     at Package (dev-error-overlay.js:6:22)
```

My environment: 1.2.2-faster-rebuilds.0, nodejs 0.10.40
I use package based architecture and add `meteor-dev-error-overlay@1.0.0` through my lib package

**Comment by brajt** [comment]
I tried the `meteor add simple:dev-error-overlay` way too, but same result.

**Comment by lassombra** [comment]
I got around this by `api.use('simple:dev-error-overlay', 'client');`

I would love to figure out why this is a problem as the offending file is supposedly client only (according to his package.js).

**Comment by stubailo** [comment]
OK, just confirmed that the package works in Meteor 1.3 beta, but not in Meteor 1.2, with the error you just pasted.

**Comment by stubailo** [comment]
Looks like we found a bug in Meteor 1.3 guys!

I just republished this package using the Meteor 1.2.1 command line tool, and it should work fine. Thanks for the report! Filed an issue on `meteor/meteor`.

**Comment by stubailo** [comment]
(Note the fixed version is published as `1.0.1`)

**Comment by brajt** [comment]
Thanks for fixing this issue. :)

**Comment by vladimir3000** [comment]
Still having the localStorage issue with Meteor 1.2.1 and simple:dev-error-overlay 1.5.1

Reverted to 1.0.1, localStorage error disappears but package does not work as expected.
