### ISSUE TITLE
[idea] Click notification to focus window/tab.

### ISSUE THREAD

**Issue by ghost** [stubailo/meteor-dev-error-overlay#2]
Clicking on the desktop notification (haven't tried on mobile) doesn't bring focus the window/tab. That'd be nice.

**Comment by stubailo** [comment]
This could be helpful for someone trying to implement this feature: https://developer.mozilla.org/en-US/docs/Web/API/Notification/onclick

**Comment by ghost** [comment]
Yes indeed. :]
